sass:
  sass_dir: assets/css

title: HiRSE_PS

collections:
  projects:
    output: true
  news:
    output: true

plugins:
  - jekyll-toc

toc:
  min_level: 2
  max_level: 2
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-
